package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BatchSheet generated by hbm2java
 */
public class BatchSheet  implements java.io.Serializable {


     private Short batchSheetId;
     private MaterialBatch materialBatch;
     private String barCode;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;

    public BatchSheet() {
    }

	
    public BatchSheet(MaterialBatch materialBatch, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.materialBatch = materialBatch;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public BatchSheet(MaterialBatch materialBatch, String barCode, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
       this.materialBatch = materialBatch;
       this.barCode = barCode;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getBatchSheetId() {
        return this.batchSheetId;
    }
    
    public void setBatchSheetId(Short batchSheetId) {
        this.batchSheetId = batchSheetId;
    }
    public MaterialBatch getMaterialBatch() {
        return this.materialBatch;
    }
    
    public void setMaterialBatch(MaterialBatch materialBatch) {
        this.materialBatch = materialBatch;
    }
    public String getBarCode() {
        return this.barCode;
    }
    
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


