package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Short clientId;
     private Address address;
     private String clientName;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set jobItems = new HashSet(0);

    public Client() {
    }

	
    public Client(Address address, String clientName, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.address = address;
        this.clientName = clientName;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public Client(Address address, String clientName, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set jobItems) {
       this.address = address;
       this.clientName = clientName;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.jobItems = jobItems;
    }
   
    public Short getClientId() {
        return this.clientId;
    }
    
    public void setClientId(Short clientId) {
        this.clientId = clientId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getJobItems() {
        return this.jobItems;
    }
    
    public void setJobItems(Set jobItems) {
        this.jobItems = jobItems;
    }




}


