package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Short contactId;
     private String contactFirstName;
     private String contactLastName;
     private String contactEmail;
     private String contactPhoneNumber;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set customerCompanies = new HashSet(0);

    public Contact() {
    }

	
    public Contact(String contactFirstName, String contactLastName, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.contactFirstName = contactFirstName;
        this.contactLastName = contactLastName;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public Contact(String contactFirstName, String contactLastName, String contactEmail, String contactPhoneNumber, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set customerCompanies) {
       this.contactFirstName = contactFirstName;
       this.contactLastName = contactLastName;
       this.contactEmail = contactEmail;
       this.contactPhoneNumber = contactPhoneNumber;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.customerCompanies = customerCompanies;
    }
   
    public Short getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Short contactId) {
        this.contactId = contactId;
    }
    public String getContactFirstName() {
        return this.contactFirstName;
    }
    
    public void setContactFirstName(String contactFirstName) {
        this.contactFirstName = contactFirstName;
    }
    public String getContactLastName() {
        return this.contactLastName;
    }
    
    public void setContactLastName(String contactLastName) {
        this.contactLastName = contactLastName;
    }
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }
    public String getContactPhoneNumber() {
        return this.contactPhoneNumber;
    }
    
    public void setContactPhoneNumber(String contactPhoneNumber) {
        this.contactPhoneNumber = contactPhoneNumber;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getCustomerCompanies() {
        return this.customerCompanies;
    }
    
    public void setCustomerCompanies(Set customerCompanies) {
        this.customerCompanies = customerCompanies;
    }




}


