package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Short countryId;
     private String country;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set cities = new HashSet(0);

    public Country() {
    }

	
    public Country(String country, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.country = country;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public Country(String country, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set cities) {
       this.country = country;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.cities = cities;
    }
   
    public Short getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }




}


