package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustomerCompany generated by hbm2java
 */
public class CustomerCompany  implements java.io.Serializable {


     private Short customerId;
     private Address address;
     private Contact contact;
     private String companyName;
     private String notes;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set jobItems = new HashSet(0);

    public CustomerCompany() {
    }

	
    public CustomerCompany(Address address, Contact contact, String companyName, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.address = address;
        this.contact = contact;
        this.companyName = companyName;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public CustomerCompany(Address address, Contact contact, String companyName, String notes, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set jobItems) {
       this.address = address;
       this.contact = contact;
       this.companyName = companyName;
       this.notes = notes;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.jobItems = jobItems;
    }
   
    public Short getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getJobItems() {
        return this.jobItems;
    }
    
    public void setJobItems(Set jobItems) {
        this.jobItems = jobItems;
    }




}


