package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * JobItem generated by hbm2java
 */
public class JobItem  implements java.io.Serializable {


     private Short jobId;
     private StockItem stockItem;
     private Client client;
     private CustomerCompany customerCompany;
     private String jobName;
     private String templateRef;
     private Date templateDate;
     private String estimateRef;
     private Date estimateDate;
     private String invoiceRef;
     private Date invoiceDate;
     private String notes;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;

    public JobItem() {
    }

	
    public JobItem(StockItem stockItem, Client client, CustomerCompany customerCompany, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.stockItem = stockItem;
        this.client = client;
        this.customerCompany = customerCompany;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public JobItem(StockItem stockItem, Client client, CustomerCompany customerCompany, String jobName, String templateRef, Date templateDate, String estimateRef, Date estimateDate, String invoiceRef, Date invoiceDate, String notes, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
       this.stockItem = stockItem;
       this.client = client;
       this.customerCompany = customerCompany;
       this.jobName = jobName;
       this.templateRef = templateRef;
       this.templateDate = templateDate;
       this.estimateRef = estimateRef;
       this.estimateDate = estimateDate;
       this.invoiceRef = invoiceRef;
       this.invoiceDate = invoiceDate;
       this.notes = notes;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Short jobId) {
        this.jobId = jobId;
    }
    public StockItem getStockItem() {
        return this.stockItem;
    }
    
    public void setStockItem(StockItem stockItem) {
        this.stockItem = stockItem;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public CustomerCompany getCustomerCompany() {
        return this.customerCompany;
    }
    
    public void setCustomerCompany(CustomerCompany customerCompany) {
        this.customerCompany = customerCompany;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public String getTemplateRef() {
        return this.templateRef;
    }
    
    public void setTemplateRef(String templateRef) {
        this.templateRef = templateRef;
    }
    public Date getTemplateDate() {
        return this.templateDate;
    }
    
    public void setTemplateDate(Date templateDate) {
        this.templateDate = templateDate;
    }
    public String getEstimateRef() {
        return this.estimateRef;
    }
    
    public void setEstimateRef(String estimateRef) {
        this.estimateRef = estimateRef;
    }
    public Date getEstimateDate() {
        return this.estimateDate;
    }
    
    public void setEstimateDate(Date estimateDate) {
        this.estimateDate = estimateDate;
    }
    public String getInvoiceRef() {
        return this.invoiceRef;
    }
    
    public void setInvoiceRef(String invoiceRef) {
        this.invoiceRef = invoiceRef;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


