package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MaterialSheet generated by hbm2java
 */
public class MaterialSheet  implements java.io.Serializable {


     private Short materialSheetId;
     private Material material;
     private String price;
     private String thickness;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set materialBatchs = new HashSet(0);

    public MaterialSheet() {
    }

	
    public MaterialSheet(Material material, String thickness, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.material = material;
        this.thickness = thickness;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public MaterialSheet(Material material, String price, String thickness, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set materialBatchs) {
       this.material = material;
       this.price = price;
       this.thickness = thickness;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.materialBatchs = materialBatchs;
    }
   
    public Short getMaterialSheetId() {
        return this.materialSheetId;
    }
    
    public void setMaterialSheetId(Short materialSheetId) {
        this.materialSheetId = materialSheetId;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getThickness() {
        return this.thickness;
    }
    
    public void setThickness(String thickness) {
        this.thickness = thickness;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getMaterialBatchs() {
        return this.materialBatchs;
    }
    
    public void setMaterialBatchs(Set materialBatchs) {
        this.materialBatchs = materialBatchs;
    }




}


