package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MaterialBatch generated by hbm2java
 */
public class MaterialBatch  implements java.io.Serializable {


     private Short materialBatchId;
     private StockItem stockItem;
     private MaterialSheet materialSheet;
     private String quantity;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set batchSheets = new HashSet(0);

    public MaterialBatch() {
    }

	
    public MaterialBatch(StockItem stockItem, MaterialSheet materialSheet, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.stockItem = stockItem;
        this.materialSheet = materialSheet;
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public MaterialBatch(StockItem stockItem, MaterialSheet materialSheet, String quantity, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set batchSheets) {
       this.stockItem = stockItem;
       this.materialSheet = materialSheet;
       this.quantity = quantity;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.batchSheets = batchSheets;
    }
   
    public Short getMaterialBatchId() {
        return this.materialBatchId;
    }
    
    public void setMaterialBatchId(Short materialBatchId) {
        this.materialBatchId = materialBatchId;
    }
    public StockItem getStockItem() {
        return this.stockItem;
    }
    
    public void setStockItem(StockItem stockItem) {
        this.stockItem = stockItem;
    }
    public MaterialSheet getMaterialSheet() {
        return this.materialSheet;
    }
    
    public void setMaterialSheet(MaterialSheet materialSheet) {
        this.materialSheet = materialSheet;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getBatchSheets() {
        return this.batchSheets;
    }
    
    public void setBatchSheets(Set batchSheets) {
        this.batchSheets = batchSheets;
    }




}


