package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Short materialId;
     private String materialType;
     private String description;
     private String notes;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set materialSheets = new HashSet(0);

    public Material() {
    }

	
    public Material(byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate) {
        this.versionNo = versionNo;
        this.userId = userId;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public Material(String materialType, String description, String notes, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set materialSheets) {
       this.materialType = materialType;
       this.description = description;
       this.notes = notes;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.materialSheets = materialSheets;
    }
   
    public Short getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Short materialId) {
        this.materialId = materialId;
    }
    public String getMaterialType() {
        return this.materialType;
    }
    
    public void setMaterialType(String materialType) {
        this.materialType = materialType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    
    public Set getMaterialSheets() {
        Set theSheets = new HashSet();       
        Iterator sheetIterator = materialSheets.iterator();
        
        while(sheetIterator.hasNext()){
            MaterialSheet theSheet = (MaterialSheet)sheetIterator.next();
            if(theSheet.isActive()){
                theSheets.add(theSheet);
            }
        }
        
        return theSheets;
    }
    
    public void setMaterialSheets(Set materialSheets) {
        this.materialSheets = materialSheets;
    }




}


