package data;
// Generated 11-Dec-2012 01:34:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StockItem generated by hbm2java
 */
public class StockItem  implements java.io.Serializable {


     private Short stockItemId;
     private short quantity;
     private Date orderedStockDate;
     private String orderRef;
     private Date receivedStockDate;
     private Date usedStockDate;
     private byte versionNo;
     private String userId;
     private Date createDate;
     private boolean active;
     private Date lastUpdate;
     private Set jobItems = new HashSet(0);
     private Set materialBatchs = new HashSet(0);

    public StockItem() {
    }

	
    public StockItem(short quantity, byte versionNo, Date createDate, boolean active, Date lastUpdate) {
        this.quantity = quantity;
        this.versionNo = versionNo;
        this.createDate = createDate;
        this.active = active;
        this.lastUpdate = lastUpdate;
    }
    public StockItem(short quantity, Date orderedStockDate, String orderRef, Date receivedStockDate, Date usedStockDate, byte versionNo, String userId, Date createDate, boolean active, Date lastUpdate, Set jobItems, Set materialBatchs) {
       this.quantity = quantity;
       this.orderedStockDate = orderedStockDate;
       this.orderRef = orderRef;
       this.receivedStockDate = receivedStockDate;
       this.usedStockDate = usedStockDate;
       this.versionNo = versionNo;
       this.userId = userId;
       this.createDate = createDate;
       this.active = active;
       this.lastUpdate = lastUpdate;
       this.jobItems = jobItems;
       this.materialBatchs = materialBatchs;
    }
   
    public Short getStockItemId() {
        return this.stockItemId;
    }
    
    public void setStockItemId(Short stockItemId) {
        this.stockItemId = stockItemId;
    }
    public short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(short quantity) {
        this.quantity = quantity;
    }
    public Date getOrderedStockDate() {
        return this.orderedStockDate;
    }
    
    public void setOrderedStockDate(Date orderedStockDate) {
        this.orderedStockDate = orderedStockDate;
    }
    public String getOrderRef() {
        return this.orderRef;
    }
    
    public void setOrderRef(String orderRef) {
        this.orderRef = orderRef;
    }
    public Date getReceivedStockDate() {
        return this.receivedStockDate;
    }
    
    public void setReceivedStockDate(Date receivedStockDate) {
        this.receivedStockDate = receivedStockDate;
    }
    public Date getUsedStockDate() {
        return this.usedStockDate;
    }
    
    public void setUsedStockDate(Date usedStockDate) {
        this.usedStockDate = usedStockDate;
    }
    public byte getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(byte versionNo) {
        this.versionNo = versionNo;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getJobItems() {
        return this.jobItems;
    }
    
    public void setJobItems(Set jobItems) {
        this.jobItems = jobItems;
    }
    public Set getMaterialBatchs() {
        return this.materialBatchs;
    }
    
    public void setMaterialBatchs(Set materialBatchs) {
        this.materialBatchs = materialBatchs;
    }




}


